server {
  listen 80;
  server_name coblog.top www.coblog.top;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name coblog.top www.coblog.top;

  root /opt/coblog/client/dist;
  index index.html;

  client_max_body_size 10m;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~ ^/(articles|auth|messages|taxonomies|uploads|ai|visits)(/.*)?$ {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  ssl_certificate /etc/letsencrypt/live/coblog.top/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/coblog.top/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
